# Generated by Django 4.1 on 2022-09-29 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=32, verbose_name='Серия')),
                ('number_passport', models.CharField(max_length=6, verbose_name='Номер паспорта')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('issue_passport', models.DateField(max_length=4, verbose_name='Дата выдачи паспорта')),
                ('code', models.CharField(max_length=64, verbose_name='Код подразделения')),
                ('birthday_place', models.CharField(max_length=256, verbose_name='Место рождения')),
                ('issued_by', models.CharField(max_length=256, verbose_name='Паспорт выдан')),
                ('snils', models.CharField(max_length=64, verbose_name='СНИЛС')),
                ('address_registration', models.CharField(max_length=256, verbose_name='Адрес регистрации (Город / Населённый пункт / Улица)')),
                ('home_registration', models.CharField(max_length=8, verbose_name='Номер дома')),
                ('flat_registration', models.CharField(max_length=8, verbose_name='Квартира')),
                ('gender', models.CharField(choices=[('Муж', 'Мужской'), ('Жен', 'Женский')], max_length=3)),
                ('checkbox_agreement', models.BooleanField(verbose_name='Заполняя сведения о СНИЛС, выражаю свое согласие на направление в электронном виде сведений обо мне в кредитную организацию для прохождения упрощенной идентификации')),
                ('address_residential', models.CharField(max_length=64, verbose_name='Адрес проживания (Город / Населённый пункт / Улица)')),
                ('address_match', models.BooleanField(verbose_name='Адрес проживания совпадает с адресом регистрации')),
                ('home_residential', models.CharField(max_length=8, verbose_name='Номер дома')),
                ('flat_residential', models.CharField(max_length=8, verbose_name='Квартира')),
            ],
            options={
                'verbose_name': 'Персональные данные пользователя',
                'verbose_name_plural': 'Персональные данные пользователей',
            },
        ),
        migrations.CreateModel(
            name='Username',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Имя')),
                ('surname', models.CharField(max_length=64, verbose_name='Отчество')),
                ('lastname', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('phone_number', models.CharField(max_length=64, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=64, verbose_name='Email адрес')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
